FROM maze-dafl

# Add scripts
ADD monitor.py /home/maze/tools/visualize_maze_cov.py
ADD get_coverage.sh /home/maze/tools/get_coverage.sh
ADD get_tcs.py /home/maze/tools/get_tcs.py
ADD convert_to_cov_code.py /home/maze/tools/convert_to_cov_code.py
ADD run_dafl.sh /home/maze/tools/run_dafl.sh
WORKDIR /home/maze/workspace
